version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: deploy/Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: LILIana0!
      POSTGRES_DB: human-detection
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
